### ISSUE TITLE
Train file contents to Txt2Vec

### ISSUE THREAD

**Issue by My-Khan** [zhongkaifu/Txt2Vec#3]
Hello sir,
what will be contents/data in train file used in Txt2vec?
1. only the token/word of original Training file OR
2. All the data of original training file e.g the Word, POS Tag and NE tag

**Comment by zhongkaifu** [comment]
If you want to train a word embedding, data #1 is the correct one.

**Comment by My-Khan** [comment]
ok sir got it.
